SELECT COUNT(*), CAST(SUM(O_TOTALPRICE) AS DECIMAL(13,2)) AS CUMULATIVE_ORDER_PRICE
FROM ORDERS O, CUSTOMER C, NATION N
WHERE O.O_CUSTKEY=C.C_CUSTKEY and C_NATIONKEY=N_NATIONKEY
GROUP BY N_NATIONKEY
ORDER BY CUMULATIVE_ORDER_PRICE DESC
;
