SELECT MKTSEGMENT1.M_MKTSEGMENT, CAST(MKTSEGMENT1.TOTAL AS DECIMAL(13,2)) AS total_F, CAST(MKTSEGMENT2.TOTAL AS DECIMAL(13,2)) AS total_O, CAST(MKTSEGMENT3.TOTAL AS DECIMAL(13,2)) AS total_P
FROM 
	(SELECT M_MKTSEGMENT, C_NAME, O_ORDERSTATUS, COUNT(*), SUM(O_TOTALPRICE) AS TOTAL
	FROM CUSTOMER C, ORDERS O, (SELECT C_MKTSEGMENT AS M_MKTSEGMENT
		FROM CUSTOMER C
		GROUP BY C_MKTSEGMENT) MKTSEGMENT
	WHERE C.C_MKTSEGMENT=M_MKTSEGMENT AND C_CUSTKEY=O_CUSTKEY
	GROUP BY M_MKTSEGMENT, O_ORDERSTATUS) MKTSEGMENT1,
	(SELECT M_MKTSEGMENT, C_NAME, O_ORDERSTATUS, COUNT(*), SUM(O_TOTALPRICE) AS TOTAL
	FROM CUSTOMER C, ORDERS O, (SELECT C_MKTSEGMENT AS M_MKTSEGMENT
		FROM CUSTOMER C
		GROUP BY C_MKTSEGMENT) MKTSEGMENT
	WHERE C.C_MKTSEGMENT=M_MKTSEGMENT AND C_CUSTKEY=O_CUSTKEY
	GROUP BY M_MKTSEGMENT, O_ORDERSTATUS) MKTSEGMENT2,
	(SELECT M_MKTSEGMENT, C_NAME, O_ORDERSTATUS, COUNT(*), SUM(O_TOTALPRICE) AS TOTAL
	FROM CUSTOMER C, ORDERS O, (SELECT C_MKTSEGMENT AS M_MKTSEGMENT
		FROM CUSTOMER C
		GROUP BY C_MKTSEGMENT) MKTSEGMENT
WHERE C.C_MKTSEGMENT=M_MKTSEGMENT AND C_CUSTKEY=O_CUSTKEY
GROUP BY M_MKTSEGMENT, O_ORDERSTATUS) MKTSEGMENT3
WHERE MKTSEGMENT1.M_MKTSEGMENT=MKTSEGMENT2.M_MKTSEGMENT AND MKTSEGMENT2.M_MKTSEGMENT=MKTSEGMENT3.M_MKTSEGMENT AND MKTSEGMENT1.O_ORDERSTATUS="F" AND MKTSEGMENT2.O_ORDERSTATUS="O" AND MKTSEGMENT3.O_ORDERSTATUS="P"
ORDER BY MKTSEGMENT1.M_MKTSEGMENT ASC
;
